FROM python

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set the working directory to /worker
WORKDIR /worker

COPY requirements.txt ./

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY worker/ .

# Expose a port if needed (if your worker communicates over a network)
EXPOSE 6379

# Run the worker (adjust as needed to run your worker script)
CMD ["python", "worker.py"]
