services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
      - redis
      - worker
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      REDIS: ${REDIS}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - '5000:5000'
    links:
        - db
        - worker
  redis:
    image: redis:5-alpine
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      REDIS: redis
      REDIS_PORT: 6379
    command: python worker.py
volumes:
  pgdata:
